server {
    listen 8099;
    server_name _;

    allow 172.30.32.2;
    deny all;

    root /app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /service-worker.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location ~* \.(?:css|js|svg|webmanifest)$ {
        expires 1h;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
